
/* type user */
export const GETALLUSERFORMAPI = "GETALLUSERFORMAPI";
export const DELATEUSERID="DELATEUSERID";
export const UPDATESTATE="UPDATESTATE";
export const UPDATEUSERID ="UPDATEUSERID";
export const FILTERUSER="FILTERUSER"



/* type prodact */
export const ADDPRODUCT ="ADDPRODUCT"
export const GETALLPRODUCT = "GETALLPRODUCT"
export const UPDATEPRODUCTSTATE="UPDATEPRODUCTSTATE"
export const DELETEPRODUCTSTATE ="DELETEPRODUCTSTATE"
export const ADDIDPRODUCTTOSTATE ="ADDIDPRODUCTTOSTATE"
export const FILTERPRODUCT ="FILTERPRODUCT"
export const GETCOMENTAIR="GETCOMENTAIR"


/*  type historique */
export const ADDISTORIQUE ="ADDISTORIQUE"
export const GETALLHISTORIQUE ="GETALLHISTORIQUE"
export const FILTERHISTORIQUE ="FILTERHISTORIQUE"
export const FILTEACTION="FILTEACTION"