export { default  as Dashbord } from './dashbored/Dahbord'
export {default  as   Addprodact } from './prodact/addprodact/addprodact'
export { default  as User } from './User/Usercontainer'
export {default as Updateuser } from './User/updateuser'
export {default as Adduser} from './User/Adduser'
export {default as Allproduct } from './prodact/allproduct'
export {default as Historiquecontainer } from './historique/historiquecontainer'
export {default  as   Updateprodact } from './prodact/updateprodact/updateprodact'
export {default as Comentaire } from './prodact/comentaire'

